website: 
  baseUrl: 'http://balneabilidade.inema.ba.gov.br/index.php/relatoriodebalneabilidade'
  homeIdx: "boletim"
  downIdx: "geraBoletim"
data:
  root: "data"
  subfolder:
    raw: "raw"
logs:
  dir: "logs"
  file: "boletins.json"